from tkinter import font as tkfont
import tkinter as tk
from PIL import Image, ImageTk


class BullsGui(object):
    '''
    Bulls and Cows GUI class
    '''

    def __init__(self, master):
        '''
        the __init__ method initializes the GUI, places all widgets on the
        interface
        '''
        master.wm_title("Bulls and Cows")
        self.load_images()
        self.master = master

        cur_row = 0
        cur_column = 0

        self.img_label = tk.Label(master, image=self.img)
        self.img_label.grid(row=cur_row, column=cur_column, sticky="ew")

        cur_column += 1
        self.rules = "==> Secret code of 4 digit will be generated by computer.\n" \
                     "==> That number does not contain any repeated digit ex. 1234.\n" \
                     "==> User has unlimited chances to guess the number.\n" \
                     "==> After each unsuccessful guess cows and bulls are displayed\n" \
                     "==> cow : digit guessed by user is at it's correct position\n" \
                     "==> bull : digit guessed by user is in the secret code but not at\n" \
                     "it's correct position.\n\n" \
                     "LET's Begin..."
        self.title_font = tkfont.Font(family="Times bold", size=10, weight="bold", slant="italic")
        self.text_font = tkfont.Font(family="Times bold", size=11, slant="italic")

        self.rules_label = tk.Label(master, text='Game Rules\n', fg='#f00', font=self.title_font)
        self.rules_label.grid(row=cur_row, column=cur_column, columnspan=6,
                              sticky='ew')

        self.rules_text = tk.Label(master, text=self.rules, fg='#9F1AAC', font=self.text_font)
        self.rules_text.grid(row=cur_row, column=cur_column, columnspan=6,
                             sticky='ew')

        cur_row += 1

        self.line = tk.Label(master,
                             text='==============================================================================================================',
                             font=self.title_font)
        self.line.configure(anchor="center")
        self.line.grid(columnspan=10, sticky='ew')

        cur_row += 1
        self.round_label = tk.Label(master, text='Round: 1', font=self.title_font, fg='#f00')
        self.round_label.configure(anchor="center")
        self.round_label.grid(row=cur_row, columnspan=10, sticky='ew')

        cur_row += 1

        vcmd = (master.register(self.on_validate), '%P', '%S')
        self.player_tip = tk.Entry(master,
                                   validate='key',
                                   justify='center',
                                   validatecommand=vcmd)
        self.player_tip.grid(row=cur_row, columnspan=10, sticky='ew')
        cur_row += 1

        self.submit_button = tk.Button(master, text='Guess', )
        self.submit_button.columnconfigure(cur_row, weight=0)
        self.submit_button.grid(row=cur_row, columnspan=10, sticky='ew')
        cur_row += 2

        self.frames = []
        for i in range(5):
            frame = tk.Frame(master, width=100, height=1)
            self.frames.append(frame)
            self.frames[i].grid(row=cur_row, column=i)

        cur_row += 1

        self.player_bull_label = tk.Label(master, image=self.bull_icon)
        self.player_bull_label.grid(row=cur_row, column=0)
        cur_column = 2
        self.player_cow_label = tk.Label(master, image=self.cow_icon)
        self.player_cow_label.grid(row=cur_row, column=cur_column)
        cur_column = 0
        cur_row += 1

        self.player_bull_count = tk.Label(master, text='0')
        self.player_bull_count.grid(row=cur_row, column=cur_column)
        cur_column = 2
        self.player_cow_count = tk.Label(master, text='0')
        self.player_cow_count.grid(row=cur_row, column=cur_column)

        cur_column = 0
        cur_row += 1

        self.game_result = tk.Label(master, text='', fg='#9F1AAC', font=self.text_font)
        self.game_result.grid(row=cur_row, column=cur_column, columnspan=5)
        cur_column = 0
        cur_row += 1

        self.new_game_button = tk.Button(master, text='New Game')
        self.new_game_button.grid(row=cur_row, column=cur_column, columnspan=10,
                                  sticky='ew')

    def load_images(self):
        '''
        loads resources (e.g. icons)
        '''
        image = Image.open(r"img/cowsbulls.png")
        resize_image = image.resize((450, 250))
        self.img = ImageTk.PhotoImage(resize_image)
        self.bull_icon = tk.PhotoImage(file=r'img/Cultures-Bull-icon.png')
        self.cow_icon = tk.PhotoImage(file=r'img/Cow-icon.png')

    def on_validate(self, P, S):
        '''
        Only digits can be entered and the string can't
        be longer than 4 digits
        '''
        if S.isdigit() and len(P) < 5:
            return True
        else:
            self.master.bell()
            return False

    def update_bulls_cows(self, player_counts):
        '''
        Updates the count labels according to the actual round
        '''
        self.player_bull_count.config(text=str(player_counts[1]))
        self.player_cow_count.config(text=(player_counts[0]))

    def update_round(self, round_number):
        '''
        Updates the round counter
        '''
        self.round_label.config(text='Round: {0}'.format(round_number))

    def reset_gui(self):
        '''
        Resets the gui
        '''
        self.update_round(1)
        self.update_bulls_cows((0, 0))
        self.game_result.config(text='')
        self.player_tip.delete(0, 'end')
